[workspace]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["yutadev31"]
repository = "https://github.com/yutadev31/cuprum-editor.git"

[workspace.dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }

[package]
name = "cuprum"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
