[package]
name = "api-macro"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
anyhow.workspace = true
syn = "2"
quote = "1"
heck = "0.5.0"
