name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build project
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose --all-targets --all-features
      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features --no-deps
      - name: Check formatting
        run: cargo fmt --all --check
